### ISSUE TITLE
按照指南集成后，报错

### ISSUE THREAD

**Issue by lpfasd123** [xuexiangjys/flutter_xupdate#109]
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1497)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1504)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
	at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:191)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Exception: Gradle task assembleDebug failed with exit code 1

> 如果以上都不能解决你的问题,那么请按照以下说明仔细填写信息,这里需要说明的是:不符合填写要求的issue一律不予理会,希望这样能节约大家的时间!

---

**问题描述（必填）**
对问题进行清晰而简明的描述，把握问题的关键点。

**使用的flutter_xupdate版本（必填）**

**如何重现（必填）**
重现的步骤:

**期望的效果**
对你期望的效果进行清晰而简明的描述。

**截图**
如果方便的话，贴一下程序截图和代码片段以帮助解释您的问题。

**设备信息**
请填写一下你运行设备的信息，信息越全越有助于我理解问题
 - 设备名: [e.g. 华为P20]
 - Android版本: [e.g. Android 7.0]
 - 设备型号 [e.g. ]
 - 系统版本（手机厂商定制rom）

**附加信息**
在此处添加任何有关该问题的任何其他说明。

**Comment by lpfasd123** [comment]
flutter_xupdate: ^3.0.0
Android： 11  sdk 31

**Comment by lpfasd123** [comment]
我是新建的计数器，然后把咱们example的main拷过来的的，就出现了这个问题

**Comment by xuexiangjys** [comment]
你这是编译器报错了，和我的库又有何相干？

**Comment by lpfasd123** [comment]
不好意思，初学乍练，我再研究下
