### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by youlongxifeng** [xuexiangjys/flutter_xupdate#6]
APP安装后闪退，没有报错内容。

**Comment by youlongxifeng** [comment]
abiFilters "armeabi","armeabi-v7a","arm64-v8a", "x86" 编译ndk加上就好了

**Comment by youlongxifeng** [comment]
但是发现单独使用这个库会报错另外一个错
Unhandled Exception: MissingPluginException(No implementation found for method checkUpdate on channel com.xuexiang/flutter_xupdate)
E/flutter (13739): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (13739): <asynchronous suspension>
E/flutter (13739): #1      FlutterXUpdate.checkUpdate (package:flutter_xupdate/flutter_xupdate.dart:133:20)
E/flutter (13739): <asynchronous suspension>
E/flutter (13739): #2      UpdatePageState.checkUpdateForce (package:demo/update/updatee_page.dart:70:20)
E/flutter (13739): #3      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:706:14)
E/flutter (13739): #4      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:789:36)
E/flutter (13739): #5      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)
E/flutter (13739): #6      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:486:11)
E/flutter (13739): #7      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:264:5)
E/flutter (13739): #8      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:199:7)
E/flutter (13739): #9      PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:467:9)
E/flutter (13739): #10     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)
E/flutter (13739): #11     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:117:9)
E/flutter (13739): #12     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (13739): #13     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:115:18)
E/flutter (13739): #14     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:101:7)
E/flutter (13739): #15     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)
E/flutter (13739): #16     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)
E/flutter (13739): #17     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)
E/flutter (13739): #18     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)
E/flutter (13739): #19     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)
E/flutter (13739): #20     _rootRunUnary (dart:async/zone.dart:1136:13)
E/flutter (13739): #21     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
E/flutter (13739): #22     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
E/flutter (13739): #23     _invoke1 (dart:ui/hooks.dart:273:10)
E/flutter (13739): #24     _dispatchPointerDataPacket (dart:ui/hooks.dart:182:5)
E/flutter (13739):

**Comment by xuexiangjys** [comment]
So what‘s your problem?
