### ISSUE TITLE
updateHttpService == null

### ISSUE THREAD

**Issue by huanlirui** [xuexiangjys/flutter_xupdate#75]
我使用：
  FlutterXUpdate.updateByInfo(updateEntity: customParseJson(data));

///将自定义的json内容解析为UpdateEntity实体类
UpdateEntity customParseJson(dynamic json) {
  UpdateInfoModel appInfo = UpdateInfoModel.fromJson(json);
  return UpdateEntity(
    hasUpdate: true,
    versionCode: 1,
    versionName: appInfo.newVersion,
    updateContent: appInfo.updateDescription,
    downloadUrl: appInfo.apkUrl,
  );
}

提示错误信息如下：

E/MethodChannel#com.xuexiang/flutter_xupdate(12255): Failed to handle method call
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): java.lang.NullPointerException: [UpdateManager.Builder] : updateHttpService == null
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at com.xuexiang.xupdate.utils.UpdateUtils.requireNonNull(UpdateUtils.java:111)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at com.xuexiang.xupdate.UpdateManager$Builder.build(UpdateManager.java:837)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at com.xuexiang.flutter_xupdate.FlutterXUpdatePlugin.updateByInfo(FlutterXUpdatePlugin.java:222)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at com.xuexiang.flutter_xupdate.FlutterXUpdatePlugin.onMethodCall(FlutterXUpdatePlugin.java:77)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:296)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$DartMessenger(DartMessenger.java:320)
E/MethodChannel#com.xuexiang/flutter_xupdate(12255): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$TsixYUB5E6FpKhMtCSQVHKE89gQ.run(Unknown Source:12)

**Comment by huanlirui** [comment]
![image](https://user-images.githubusercontent.com/40491203/150942917-e653aec1-4727-4b69-a88d-d299adcbf18a.png)

**Comment by huanlirui** [comment]
不好意思。初始化没整对。现在Ok了
